import cilling from "./img/false-ceiling-interior-design-idea-07.jpg";
import cilling2 from "./img/845eb937006335.5731a981ed4b8.jpg";
import cilling3 from "./img/WhatsApp-Image-2020-11-12-at-13.38.25-2.jpeg";
import wall2 from "./img/2053687.jpg";
import wall3 from "./img/tekstura-fon-abstraktsiia-abstract-texture-background-rose-g.jpg";
import wall4 from "./img/WALL-TEXTURE-FEATURE-compressed.jpg";
import wall5 from "./img/well.png";
import wall7 from "./img/texture.png";
import wall8 from "./img/abstract-malachite-green-background-fake-agate-golden-veins-painted-artificial-stone-texture-marbled-surface-digital-marbling-196999775.jpg";
import wall9 from "./img/photo-1617967398617-a08eea39aa48.jpg";
import wall10 from "./img/360_F_453810576_0TuCFTlEPxaQ4sx2eqOzKDlFyIZc3BF9.jpg";
import wall11 from "./img/texture-background.jpg";
import wall12 from "./img/4588497.png";
import wall13 from "./img/background-textures.png";
import wall14 from "./img/Free-Polygonal-Low-Poly-Background-Texture.png";
import wall15 from "./img/31892588cc5aef84ff4f5ca2d503c562.gif";
import wall16 from "./img/3d-textures.png";
import wall17 from "./img/GettyImages-486522988-58e6b3505f9b58ef7e1b092d.jpg";
import wall18 from "./img/10064255-56a03d5f5f9b58eba4af78f4.jpg";
import wall19 from "./img/indieground_abstract_textures_main_02.jpg";
import wall20 from "./img/colorful-marble-paint-background_23-2148491625.jpg";
import wall21 from "./img/LP_Texture_04.png";
import wall22 from "./img/digital-embossing-true-texture.jpg";
import wall23 from "./img/003319-Brick-Wall-Renovated-Free-Texture.png";
import wall24 from "./img/photo-1620393470010-fd62b8ab841d.jpg";
import wall25 from "./img/pngtree-gold-marble-texture-background-image_115783.jpg";
import wall26 from "./img/texture-measurement-using-texture-pro-for-ct3.jpg";
import wall27 from "./img/photoshop-water-texture-31614175576.jpg";
import wall28 from "./img/abstract-colorful-textured-fractal-lines-neon-colors_78240-359.jpg";
import wall29 from "./img/colorful-organic-seamless-pattern-texture-vector.png";
import wall30 from "./img/creative-seamless-pattern-with-hand-drawn-textures_1273-689.jpg";
import wall31 from "./img/pngtree-wood-texture-background-picture-image_1236640.jpg";
import wall32 from "./img/Mockup-Texture2.jpg";

import doorImage from "./img/4bf02906d8b7f0a3446edf0ccf4296c8.jpg";
import doorImage2 from "./img/rf.jpg";
import doorImage3 from "./img/10-sagwan-chokhat-500x500.jpg";
import doorImage4 from "./img/BN9G32.jpg";
import doorImage5 from "./img/8pane DOUBLE(1).jpg";
import windowImage from "./img/monsey-glass-windows.jpg";
import windowImageBack from "./img/single-pane-versus-dual-pane-windows-in-sydney.jpg";
import sideWall from "./img/depositphotos_392505906-stock-photo-light-abstract-wall-background-copy.jpg";
import sideWall2 from "./img/grey-grainy-wall-texture-monochromatic-plaster-bright-sun-147638989.jpg";
import marble from "./img/marble.jpg";
import marble2 from "./img/5-things-to-keep-in-mind-while-choosing-floor-tiles-840x480.jpg";

export const Data = [
  {
    room: 1,
    topCilling: cilling,
    toiletWall: wall2,
    leftWall: wall3,
    entranceDoorImage: doorImage,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: sideWall,
    floorImg: marble,
  },
  {
    room: 2,
    topCilling: cilling2,
    toiletWall: marble,
    leftWall: wall4,
    entranceDoorImage: doorImage2,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall5,
    floorImg: marble,
  },
  {
    room: 3,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: sideWall2,
    entranceDoorImage: doorImage3,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall5,
    floorImg: marble2,
  },
  {
    room: 4,
    topCilling: cilling3,
    toiletWall: wall28,
    leftWall: wall27,
    entranceDoorImage: doorImage4,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall27,
    floorImg: marble2,
  },
  {
    room: 5,
    topCilling: cilling3,
    toiletWall: marble,
    leftWall: wall7,
    entranceDoorImage: doorImage5,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall7,
    floorImg: marble2,
  },
  {
    room: 6,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall8,
    entranceDoorImage: doorImage,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall8,
    floorImg: marble2,
  },
  {
    room: 7,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall9,
    entranceDoorImage: doorImage2,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall9,
    floorImg: marble2,
  },
  {
    room: 8,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall10,
    entranceDoorImage: doorImage3,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall10,
    floorImg: marble,
  },
  {
    room: 9,
    topCilling: cilling3,
    toiletWall: wall2,
    leftWall: wall12,
    entranceDoorImage: doorImage4,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall12,
    floorImg: marble,
  },
  {
    room: 10,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall13,
    entranceDoorImage: doorImage5,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall13,
    floorImg: marble,
  },
  {
    room: 11,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall14,
    entranceDoorImage: doorImage,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall14,
    floorImg: marble,
  },
  {
    room: 12,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall15,
    entranceDoorImage: doorImage2,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall15,
    floorImg: marble,
  },
  {
    room: 13,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall16,
    entranceDoorImage: doorImage3,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall16,
    floorImg: marble,
  },
  {
    room: 14,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall11,
    entranceDoorImage: doorImage4,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall11,
    floorImg: marble,
  },
  {
    room: 15,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall17,
    entranceDoorImage: doorImage5,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall17,
    floorImg: marble,
  },
  {
    room: 16,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall18,
    entranceDoorImage: doorImage,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall18,
    floorImg: marble,
  },
  {
    room: 17,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall19,
    entranceDoorImage: doorImage2,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall19,
    floorImg: marble,
  },
  {
    room: 18,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall20,
    entranceDoorImage: doorImage3,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall20,
    floorImg: marble,
  },
  {
    room: 19,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall21,
    entranceDoorImage: doorImage4,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall21,
    floorImg: marble,
  },
  {
    room: 20,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall22,
    entranceDoorImage: doorImage5,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall22,
    floorImg: marble,
  },
  {
    room: 21,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall23,
    entranceDoorImage: doorImage,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall23,
    floorImg: marble,
  },
  {
    room: 22,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall24,
    entranceDoorImage: doorImage2,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall24,
    floorImg: marble,
  },
  {
    room: 23,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall25,
    entranceDoorImage: doorImage3,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall25,
    floorImg: marble,
  },
  {
    room: 24,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall26,
    entranceDoorImage: doorImage4,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall26,
    floorImg: marble,
  },
  {
    room: 25,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall27,
    entranceDoorImage: doorImage5,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall27,
    floorImg: marble,
  },
  {
    room: 26,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall28,
    entranceDoorImage: doorImage,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall28,
    floorImg: marble,
  },
  {
    room: 27,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall29,
    entranceDoorImage: doorImage2,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall29,
    floorImg: marble,
  },
  {
    room: 28,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall30,
    entranceDoorImage: doorImage3,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall30,
    floorImg: marble,
  },
  {
    room: 29,
    topCilling: cilling3,
    toiletWall: wall12,
    leftWall: wall31,
    entranceDoorImage: doorImage4,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall,
    rightsideWall: wall31,
    floorImg: marble,
  },
  {
    room: 30,
    topCilling: cilling3,
    toiletWall: wall27,
    leftWall: wall32,
    entranceDoorImage: doorImage5,
    frontWindow: windowImage,
    windowImageBack: windowImageBack,
    sideWall: sideWall2,
    rightsideWall: wall32,
    floorImg: marble,
  },
];
